### ISSUE TITLE
It would be great to see GSTouchesShowingWindow converted to Swift, some of us are trying to go 100% Swift!  :-)

### ISSUE THREAD

**Issue by curveddesign** [LukasCZ/GSTouchesShowingWindow#2]
It would be great to see GSTouchesShowingWindow converted to Swift, some of us are trying to go 100% Swift!  :-)

**Comment by LukasCZ** [comment]
You're right, it would be good to convert it to Swift, but unfortunately I haven't started with Swift yet, so it would be quite difficult for me. But if you know at least basics of Obj-C, you could convert it yourself. I think it shouldn't be that difficult ;-).

**Comment by idokleinman** [comment]
problem is with integration within AppDelegate (override window etc)

**Comment by LukasCZ** [comment]
@curveddesign I know I'm way too late, but I have good news: In my efforts to finally start with Swift, I've created a new version of this code which is entirely in Swift (here: [GSTouchesShowingWindow-Swift](https://github.com/LukasCZ/GSTouchesShowingWindow-Swift)). It also supports App Extensions and shows a short tap indicator.
