### ISSUE TITLE
How to get it to work with Swift project?

### ISSUE THREAD

**Issue by idokleinman** [LukasCZ/GSTouchesShowingWindow#3]

**Comment by mbeaty** [comment]
I started getting the following errors when I upgraded to Swift 1.2.

"Objective-C method 'window' provided by getter for 'window' conflicts with optional requirement getter for 'window' in protocol 'UIApplicationDelegate'"

I got it to work by doing this:

```
static var showTouchesWindow: GSTouchesShowingWindow? = {
    return GSTouchesShowingWindow(frame: UIScreen.mainScreen().bounds)
}()

var window: UIWindow? = showTouchesWindow
```

**Comment by curveddesign** [comment]
Wow mbeaty!  I was getting the same error and could not figure it out for the life of me!  That works in my Swift 1.2 version too!

**Comment by mbeaty** [comment]
Ha, well, I don't know why I didn't try this in the first place, but this works too:

```
var window: UIWindow? = GSTouchesShowingWindow(frame: UIScreen.mainScreen().bounds)
```

**Comment by LukasCZ** [comment]
There's now a dedicated Swift 3.0 version of GSTouchesShowingWindow with instructions on how to get it working, you can check it out here: [https://github.com/LukasCZ/GSTouchesShowingWindow-Swift](https://github.com/LukasCZ/GSTouchesShowingWindow-Swift). So I'm closing this Issue for now.
