### ISSUE TITLE
Cannot import into Swift project

### ISSUE THREAD

**Issue by jayisidoro** [LukasCZ/GSTouchesShowingWindow#9]
Is there a swift demo project that shows how to incorporate this into an existing project?

I've copied both the .h/.m files along with the PNG. I've tried importing through a bridging header, so when I begin to type in the "import GSTouchesShowingWindow" in the app delegate, it doesn't recognize it. I'm not sure if the files have to be in a specific level within the project, but I'm not able to get this to work on my app. Any suggestions?

**Comment by LukasCZ** [comment]
I'm sorry for only getting to this now, this repository wasn't exactly high on my list of priorities.
I have good news though: I've created a new version of this code which is entirely in Swift. It's in a separate repository: [GSTouchesShowingWindow-Swift](https://github.com/LukasCZ/GSTouchesShowingWindow-Swift). It also has detailed instructions on how to get it working in a Swift project.
